### ISSUE TITLE
How many BoF Dinner assistants needed?

### ISSUE THREAD

**Issue by ChrisFreeman** [ChrisFreeman/pydx-volunteer-2015-issues#11]
Currently there are 8 on the volunteer grid: http://volunteer.pydx.org:8081/volunteer/grid/

Is 8 the correct number?

**Comment by capnleela** [comment]
Hi Chris,
We discussed this tonight and, unless we get 50 new people registered in
the next week, we're likely going to only need at most 2 volunteers for
this shift.

Thank you for getting the app out!

**Comment by ChrisFreeman** [comment]
Change max volunteers to two from 8.
